_target_: birdset.modules.embedding_module.EmbeddingModule

defaults:
  - _self_
  - embedding_model: ../network/perch_logreg.yaml

#embedding_model: perch_logreg.yaml

network:
  model:
    _target_: "torch.nn.Linear"
    in_features: ${module.embedding_model.embedding_size}
    out_features: ${datamodule.dataset.n_classes}

  model_name: ${module.embedding_model.model_name}_embedding # Most values are just taken from embedding model as it is the first part
  model_type: ${module.embedding_model.model_type}
  torch_compile: ${module.embedding_model.torch_compile}
  sampling_rate: ${module.embedding_model.sampling_rate}
  normalize_spectrogram: ${module.embedding_model.normalize_spectrogram}
  normalize_waveform: ${module.embedding_model.normalize_waveform} 

task: multiclass
#class_weights_loss: ${datamodule.dataset.class_weights_loss}
num_gpus: ${trainer.devices}

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-5
  _partial_: true
  weight_decay: 0.01

loss:
  _target_: torch.nn.CrossEntropyLoss

metrics: 
  _target_: birdset.modules.metrics.multiclass.EmbeddingMetricsConfig # Temporary solution 
  num_labels: ${datamodule.dataset.n_classes}

output_activation: 
  _target_: "torch.sigmoid" # Use sigmoid like Ghani et al
  _partial_: true

logging_params:
  _target_: birdset.modules.base_module.LoggingParamsConfig 
  on_step: False
  on_epoch: True
  sync_dist: False
  prog_bar: True  