_target_: birdset.modules.embedding_module.EmbeddingModule

defaults:
  - _self_
  - embedding_model: ../network/perch_logreg.yaml

#embedding_model: perch_logreg.yaml

network:
  model:
    _target_: "torch.nn.Linear"
    in_features: 1280 # From perch
    out_features: ${datamodule.dataset.n_classes}

  model_name: perch_classifier
  model_type: waveform
  torch_compile: False
  sampling_rate: 32_000 #${embedding_model.sampling_rate}
  normalize_spectrogram: False
  normalize_waveform: null  

task: multiclass
#class_weights_loss: ${datamodule.dataset.class_weights_loss}
num_gpus: ${trainer.devices}

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-5
  _partial_: true
  weight_decay: 0.01

loss:
  _target_: torch.nn.BCEWithLogitsLoss

metrics: 
  _target_: birdset.modules.metrics.multiclass.EmbeddingMetricsConfig # Temporary solution 
  num_labels: ${datamodule.dataset.n_classes}

output_activation: 
  _target_: "torch.sigmoid" # Use sigmoid like Ghani et al
  _partial_: true

logging_params:
  _target_: birdset.modules.base_module.LoggingParamsConfig 
  on_step: False
  on_epoch: True
  sync_dist: False
  prog_bar: True  