_target_: biofoundation.datamodule.components.transforms.biolingual_transforms.BioLingualTransformsWrapper
sample_rate: ${module.network.sample_rate}
model_type: ${module.network.model_type}
task: ${datamodule.dataset.task}
max_length: 5

defaults:
  - _self_
  - preprocessing: default.yaml 
  - waveform_augmentations: default.yaml
  - spectrogram_augmentations: default.yaml
  - decoding: bird_event_decoder.yaml
  - feature_extractor: default_aug.yaml
  - nocall_sampler: null
  



