model: 
  _target_: biofoundation.modules.models.audiomae.AudioMAEModel
  num_classes: null
  
model_name: audio_mae
model_type: waveform
torch_compile: False
sample_rate: 16_000
normalize_spectrogram: False
normalize_waveform: False
embedding_size: 768
length: 10