model:
  _target_: birdset.modules.models.aves.AvesClassifier
  num_classes: null
  local_checkpoint: null
  pretrain_info:
    hf_path: ${datamodule.dataset.hf_path}
    hf_name: ${datamodule.dataset.hf_name}
    hf_pretrain_name: null
    valid_test_only: False
  
model_name: aves
model_type: waveform
torch_compile: False
sampling_rate: 16_000
normalize_spectrogram: False
normalize_waveform: False
embedding_size: 768
length: 15 
# hubert uses the w2v2 featue extractor 






