model: 
  _target_: biofoundation.modules.models.beats.BEATsModel
  num_classes: null

model_name: BEATs_NatureLM
model_type: waveform
torch_compile: False
sample_rate: 16_000
normalize_spectrogram: False
normalize_waveform: False
embedding_size: 768
length: 10

