model:
  _target_: biofoundation.modules.models.biolingual.BioLingualClassifier
  num_classes: null
  checkpoint: davidrrobinson/BioLingual
  local_checkpoint: null
  pretrain_info:
    hf_path: ${datamodule.dataset.hf_path}
    hf_name: ${datamodule.dataset.hf_name}
    hf_pretrain_name: null
    valid_test_only: False
  device: ${trainer.devices[0]}
  
model_name: biolingual
model_type: waveform
torch_compile: False
sample_rate: 48_000
normalize_spectrogram: False
normalize_waveform: False
embedding_size: 768
length: 10 






