model:
  _target_: biofoundation.modules.models.convnext.ConvNextModule
  num_classes: null
  num_channels: 1
  checkpoint: DBD-research-group/ConvNeXT-Base-BirdSet-XCL
  local_checkpoint: null
  cache_dir: ${paths.dataset_path}/models/
  preprocess_in_model: True
  classifier: nul
  pretrain_info:
    hf_path: ${datamodule.dataset.hf_path}
    hf_name: ${datamodule.dataset.hf_name}
    hf_pretrain_name: null
    valid_test_only: False
  

model_name: convnext_bs
model_type: vision
torch_compile: False
sample_rate: 32_000
normalize_waveform: null
normalize_spectrogram: True
embedding_size: 1024
length: 5













