model_name: "eat"
model:
  _target_: biofoundation.modules.models.eat_soundnet.EAT
  nf: 32
  seq_len: 110250
  embedding_size: 256
  n_layers: 6
  nhead: 16
  factors: [4, 4, 4, 4]
  num_classes: ${datamodule.dataset.n_classes}
  dim_feedforward: 2048
  pretrain_info: null
  
torch_compile: False
model_type: waveform
sampling_rate: 22050
normalize_spectrogram: False
normalize_waveform: instance_min_max
embedding_size: 256
length: 5
