model: 
  _target_: biofoundation.modules.models.perch.PerchModel
  num_classes: null
  tfhub_version: 8
  classifier : null
  restrict_logits: True
  label_path: ${paths.root_dir}/resources/perch/label_updated.csv
  pretrain_info:
    hf_path: ${datamodule.dataset.hf_path}
    hf_name: ${datamodule.dataset.hf_name}
    hf_pretrain_name: null
    valid_test_only: False

model_name: perch
model_type: waveform
torch_compile: False
sample_rate: 32_000
normalize_spectrogram: False
normalize_waveform: "instance_peak_normalization"
embedding_size: 1280
length: 5