model:
  _target_: biofoundation.modules.models.ssast.ASTModel
  num_classes: null
  load_pretrained_mdl_path: ${paths.root_dir}/models/ssast/SSAST-Base-Patch-400.pth
  model_size: base
  pretrain_stage: False
  fstride: 10 # The stride of patch spliting on the frequency dimension, for 16*16 patchs, fstride=16 means no overlap, fstride=10 means overlap of 6.
  tstride: 10 # The stride of patch spliting on the time dimension, for 16*16 patchs, tstride=16 means no overlap, tstride=10 means overlap of 6.
  input_tdim: 500 # The number of time frames of the input spectrogram.
  
model_name: ssast
model_type: waveform # Spectrogram creation is done in the model itself
torch_compile: False
sample_rate: 16_000
normalize_spectrogram: False
normalize_waveform: False
embedding_size: 768
length: 5 # Change if input_tdim is changed

