model: 
  _target_: biofoundation.modules.models.vit.ViTModel
  num_classes: null
  

model_name: vit
model_type: waveform
torch_compile: False
sampling_rate: 22_050
normalize_spectrogram: False
normalize_waveform: False
embedding_size: 768
length: 3