model: 
  _target_: biofoundation.modules.models.vit_inatsound.Vit_iNatSoundModel
  num_classes: null
  

model_name: vit_inatsound
model_type: waveform
torch_compile: False
sample_rate: 22_050
normalize_spectrogram: False
normalize_waveform: False
embedding_size: 768
length: 3