model: 
  _target_: biofoundation.modules.models.vit_inatsound.Vit_iNatSoundModel
  checkpoint_path: '/workspace/models/vit/vit_single_mixup.pt'
  num_classes: null
  pooling: 'just_cls'
  

model_name: vit_inatsound
model_type: waveform
torch_compile: False
sample_rate: 22_050
normalize_spectrogram: False
normalize_waveform: False
embedding_size: 768
length: 3