model: 
  _target_: birdset.modules.models.audiomae.AudioMAEModel
  num_classes: null
  train_classifier: True

model_name: audio_mae
model_type: waveform
torch_compile: False
sampling_rate: 16_000
normalize_spectrogram: False
normalize_waveform: False
embedding_size: 768
length: 10