model:
  _target_: birdset.modules.models.aves.AvesClassifier
  model_path: ${paths.root_dir}/models/aves/aves-base-bio.torchaudio.pt
  config_path: ${paths.root_dir}/models/aves/aves-base-bio.torchaudio.model_config.json
  local_checkpoint: null
  num_classes: null
  pretrain_info:
    hf_path: ${datamodule.dataset.hf_path}
    hf_name: ${datamodule.dataset.hf_name}
    hf_pretrain_name: null
    valid_test_only: False
  
model_name: aves
model_type: waveform
torch_compile: False
sampling_rate: 16_000 # Or 16k (performed 2% worse)
normalize_spectrogram: False
normalize_waveform: False
embedding_size: 768
length: 15 
# hubert uses the w2v2 featue extractor 






