# Should have the correct values from BirdNET Paper
model: 
  _target_: birdset.modules.models.birdnet.BirdNetModel
  num_classes: ${datamodule.dataset.n_classes}
  train_classifier: True
  model_path: ${paths.root_dir}/checkpoints/birdnet/BirdNET_GLOBAL_6K_V2.4_Model

model_name: birdnet_embedding
model_type: waveform
torch_compile: False
sampling_rate: 48_000
normalize_spectrogram: False
normalize_waveform: null