model:
  _target_: birdset.modules.models.ltu.LTU
  checkpoint: null # ADD 
  folder_path: ${paths.root_dir}/models/ltu
  local_checkpoint: null
  num_classes: null
  cache_dir: ${paths.model_path}
  pretrain_info:
    hf_path: ${datamodule.dataset.hf_path}
    hf_name: ${datamodule.dataset.hf_name}
    hf_pretrain_name: null
    valid_test_only: False


model_name: ltu
model_type: waveform
torch_compile: False
sampling_rate: 16_000
normalize_spectrogram: False
normalize_waveform: False
embedding_size: 768
length: 10