model: 
  _target_: birdset.modules.models.LTU.LTU
  num_classes: ${datamodule.dataset.n_classes}
  tfhub_version: 4
  train_classifier: True
  restrict_logits: False
  label_path: ${paths.root_dir}/resources/LTU/label_updated.csv
  task: ${module.task}
  gpu_to_use: ${trainer.devices[0]}
  #pretrain_info:
   # hf_path: ${datamodule.dataset.hf_path}
    #hf_name: ${datamodule.dataset.hf_name}
   # hf_pretrain_name: null

model_name: LTU
model_type: waveform
torch_compile: False
sampling_rate: 32_000
normalize_spectrogram: False
normalize_waveform: "instance_peak_normalization"
embedding_size: 1280