model:
  _target_: birdset.modules.models.ssast.ASTModel
  load_pretrained_mdl_path: ${paths.root_dir}/checkpoints/ssast/SSAST-Base-Patch-400.pth
  model_size: base
  label_dim: ${datamodule.dataset.n_classes}
  pretrain_stage: False
  fstride: 10
  tstride: 10
  input_tdim: 500
  



model_name: ssast
model_type: vision
torch_compile: False
sampling_rate: 32_000
normalize_spectrogram: True
normalize_waveform: "instance_normalization"
embedding_size: 768














