_target_: birdset.datamodule.birdset_datamodule.BirdSetDataModule

defaults: 
  - _self_
  - transforms: bird_default.yaml
  - loaders: default.yaml
  - mapper: xc_bambird_mapper.yaml


dataset:
  data_dir: ${paths.dataset_path}
  dataset_name: nips
  hf_path: DBD-research-group/birdset_v1
  hf_name: nips
  seed: ${seed}
  n_classes: 53
  n_workers: 3
  val_split: 0.2
  task: ${module.task}
  subset: null
  sampling_rate: ${module.network.sampling_rate}
  classlimit: 500
  eventlimit: 5



