_target_: biofoundation.datamodule.audioset_datamodule.AS20DataModule

defaults: 
  - _self_
  - transforms: esc_default.yaml # For now
  - loaders: default.yaml

dataset:
  data_dir: ${paths.dataset_path}
  dataset_name: audioset_20k
  hf_path: confit/audioset-20k-wds
  hf_name: default
  seed: ${seed}
  n_classes: 527
  n_workers: 1
  val_split: 0.1
  task: ${module.task}
  subset: null
  sample_rate: ${module.network.sample_rate}
  class_weights_loss: null
  class_weights_sampler: null
  classlimit: null
  eventlimit: null
  use_test_as_valid: False  