#ESC50
_target_: biofoundation.datamodule.esc50_embedding_datamodule.ESC50EmbeddingDataModule

defaults:
  - _self_
  - transforms: esc_default.yaml
  - loaders: default.yaml
  - embedding_model: ../../module/network/perch_logreg.yaml
  

dataset:
  data_dir: ${paths.dataset_path}
  dataset_name: esc50
  hf_path: ashraq/esc50
  hf_name: default
  seed: ${seed}
  n_classes: 50
  n_workers: 1
  val_split: 0.2
  task: ${module.task}
  subset: null
  sampling_rate: ${module.network.sampling_rate}
  class_weights_loss: False
  class_weights_sampler: null




k_samples: 0
gpu_to_use: ${trainer.devices[0]} 