_target_: birdset.datamodule.pretrain_embedding_datamodule.PretrainEmbeddingDataModule

defaults: 
  - _self_
  - transforms: bird_default.yaml
  - loaders: default.yaml
  - mapper: xc_bambird_mapper.yaml
  - embedding_model: ../../module/network/convnext.yaml

dataset:
  data_dir: ${paths.dataset_path}
  dataset_name: XCL
  hf_path: DBD-research-group/BirdSet
  hf_name: XCL
  seed: ${seed}
  n_workers: 5
  val_split: null
  task: ${module.task}
  subset: null
  sampling_rate: ${module.network.sampling_rate}
  class_weights_loss: null
  class_weights_sampler: null
  classlimit: 500
  eventlimit: 5
  direct_fingerprint: null

k_samples: 0
gpu_to_use: ${trainer.devices[0]} 