_target_: birdset.datamodule.components.transforms.EmbeddingTransforms
sampling_rate: ${module.network.sampling_rate}
model_type: ${module.network.model_type}
task: ${datamodule.dataset.task}
max_length: ${module.embedding_model.length}
embedding_model: ${module.embedding_model}

defaults:
  - _self_
  - preprocessing: default.yaml 
  - waveform_augmentations: default.yaml
  - spectrogram_augmentations: default.yaml
  - decoding: bird_event_decoder.yaml
  - feature_extractor: default_aug.yaml
  - nocall_sampler: null